import 'dart:math';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

import '../l10n/app_strings.dart';

/// Lets the user type their name and turn it into a signature-style image
/// by picking one of a few script/calligraphic fonts — the "generate from
/// name" alternative to drawing one by hand (see `SignaturePadPage`) or
/// picking a photo. Pops with a transparent PNG of just the rendered name,
/// same shape as the other two sources, so it flows into the exact same
/// placement pipeline (`EditorScreen._beginStampPlacement`) — including the
/// existing ink-bounds crop, which trims the extra transparent margin
/// around whatever length name was typed automatically.
class TypeSignaturePadPage extends StatefulWidget {
  const TypeSignaturePadPage({super.key});

  @override
  State<TypeSignaturePadPage> createState() => _TypeSignaturePadPageState();
}

class _SignatureFontStyle {
  const _SignatureFontStyle(
    this.label,
    this.fontFamily, {
    required this.supportsGreek,
    required this.supportsLatin,
    this.fontSize = 42,
  });

  final String label;
  final String fontFamily;
  // None of the free connected-cursive "signature" fonts out there
  // (Google Fonts' whole Handwriting category included) ship any Greek
  // glyphs at all — it's just not a script those typefaces were drawn for.
  // Conversely SigFrederika (below) is a genuine Greek calligraphy face and
  // has no Latin glyphs at all. So each style declares which script(s) it
  // actually has glyphs for, and [_visibleStyles] filters to whichever
  // matches what's typed — never offering a style that would render as
  // tofu boxes or a plain fallback font.
  final bool supportsGreek;
  final bool supportsLatin;
  final double fontSize;
}

/// One randomized "personal touch" pass applied on top of a chosen font —
/// a small whole-signature tilt, regenerated by the shuffle button. It's
/// deliberately whole-word, not per-letter jitter or letter-spacing: every
/// one of these fonts is a *connected* cursive/calligraphic face, where
/// letters are drawn to flow into each other, so nudging individual glyphs
/// apart would just break the joins that make it look hand-signed in the
/// first place. This makes two shuffles of the same name look like two
/// slightly different signatures — the way no two people (or even the same
/// person twice) sign identically.
class _SignatureVariant {
  const _SignatureVariant({required this.rotation});

  final double rotation; // radians
}

class _TypeSignaturePadPageState extends State<TypeSignaturePadPage> {
  static const List<_SignatureFontStyle> _styles = [
    _SignatureFontStyle('Elegant', 'SigGreatVibes', supportsGreek: false, supportsLatin: true),
    _SignatureFontStyle('Flowing', 'SigSacramento', supportsGreek: false, supportsLatin: true),
    _SignatureFontStyle('Bold script', 'SigAlexBrush', supportsGreek: false, supportsLatin: true),
    _SignatureFontStyle('Classic', 'SigAllura', supportsGreek: false, supportsLatin: true, fontSize: 46),
    // Wider spread of moods added after comparing against a signature-style
    // gallery site — bold/energetic, thin/formal, rounded/casual, classic
    // elegant loops, and plain everyday handwriting, so a Latin name has
    // real variety instead of four fonts that all read as "the same".
    _SignatureFontStyle('Bold & confident', 'SigYellowtail', supportsGreek: false, supportsLatin: true, fontSize: 40),
    _SignatureFontStyle('Delicate', 'SigMrsSaintDelafield', supportsGreek: false, supportsLatin: true, fontSize: 44),
    _SignatureFontStyle('Rounded', 'SigPacifico', supportsGreek: false, supportsLatin: true, fontSize: 34),
    _SignatureFontStyle('Timeless', 'SigTangerine', supportsGreek: false, supportsLatin: true, fontSize: 56),
    _SignatureFontStyle('Balanced', 'SigDancingScript', supportsGreek: false, supportsLatin: true, fontSize: 40),
    _SignatureFontStyle('Everyday', 'SigCaveat', supportsGreek: false, supportsLatin: true, fontSize: 40),
    _SignatureFontStyle('Handwritten', 'SigHomemadeApple', supportsGreek: false, supportsLatin: true, fontSize: 28),
    // The one genuinely hand-signed-looking Greek option — a real
    // connected calligraphy face, not just a slanted print font. Shown
    // first among the Greek-capable styles so it's the default pick.
    _SignatureFontStyle('Signature', 'SigFrederika', supportsGreek: true, supportsLatin: false, fontSize: 40),
    _SignatureFontStyle('Formal', 'SigEBGaramond', supportsGreek: true, supportsLatin: true),
    _SignatureFontStyle('Literary', 'SigAlegreya', supportsGreek: true, supportsLatin: true),
    _SignatureFontStyle('Greek Classic', 'SigGFSNeohellenic', supportsGreek: true, supportsLatin: true),
  ];

  final TextEditingController _nameController = TextEditingController();
  // Keyed by font family (stable) rather than list position — the visible
  // style list changes length depending on what's typed (see
  // [_visibleStyles]), so a plain index would point at the wrong tile, or
  // out of range, the moment the list shrinks or grows.
  final Map<String, GlobalKey> _boundaryKeys = {
    for (final style in _styles) style.fontFamily: GlobalKey(),
  };
  String _selectedFamily = _styles.first.fontFamily;

  // Bumped by the shuffle button; every tile's [_SignatureVariant] is
  // derived from this plus its own font family, so one tap regenerates a
  // fresh tilt for every visible style at once, deterministically (same
  // seed -> same look, so rebuilds from unrelated setState calls, like
  // typing another letter, don't make the signature drift on you).
  int _variantSeed = 0;

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  bool get _isGreekName {
    final text = _nameController.text;
    // Greek and Coptic Unicode block — covers modern monotonic Greek,
    // which is what a typed name will actually use.
    return text.runes.any((r) => r >= 0x0370 && r <= 0x03FF);
  }

  List<_SignatureFontStyle> get _visibleStyles => _isGreekName
      ? _styles.where((s) => s.supportsGreek).toList()
      : _styles.where((s) => s.supportsLatin).toList();

  _SignatureVariant _variantFor(String fontFamily) {
    final rnd = Random(_variantSeed * 92821 + fontFamily.hashCode);
    final degrees = (rnd.nextDouble() - 0.5) * 6; // -3..3 degrees of tilt
    return _SignatureVariant(rotation: degrees * pi / 180);
  }

  void _shuffle() => setState(() => _variantSeed++);

  Future<void> _use() async {
    final name = _nameController.text.trim();
    if (name.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(AppStrings.of(context).typeNameFirst)),
      );
      return;
    }
    try {
      final boundary = _boundaryKeys[_selectedFamily]!
          .currentContext!
          .findRenderObject() as RenderRepaintBoundary;
      // Same pixel ratio as the hand-drawn pad, for the same reason: stays
      // crisp once the signature is later stretched to whatever size the
      // user resizes it to on the page. Whatever tilt is showing on screen
      // right now is exactly what gets captured — no separate "final"
      // render step.
      final image = await boundary.toImage(pixelRatio: 3.0);
      final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      if (byteData == null) return;
      if (mounted) {
        Navigator.pop(
          context,
          byteData.buffer.asUint8List(byteData.offsetInBytes, byteData.lengthInBytes),
        );
      }
    } catch (e, st) {
      debugPrint('[TypeSignaturePad] capture failed: $e\n$st');
    }
  }

  @override
  Widget build(BuildContext context) {
    final visible = _visibleStyles;
    // If what's typed just switched between Greek/Latin, the previously
    // selected style may no longer be on the (now filtered) list — fall
    // back to the first visible one rather than pointing at a hidden tile.
    if (!visible.any((s) => s.fontFamily == _selectedFamily)) {
      _selectedFamily = visible.first.fontFamily;
    }
    final greekFiltered = _isGreekName;
    final s = AppStrings.of(context);

    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.close),
          tooltip: s.cancel,
          onPressed: () => Navigator.pop(context),
        ),
        title: Text(s.typeSignature),
        actions: [
          IconButton(
            icon: const Icon(Icons.shuffle),
            tooltip: s.shuffleStyle,
            onPressed: _shuffle,
          ),
          Padding(
            padding: const EdgeInsets.only(right: 12),
            child: IconButton(
              icon: const Icon(Icons.check_circle),
              tooltip: s.use,
              onPressed: _use,
              style: IconButton.styleFrom(
                backgroundColor: Colors.green.shade50,
                foregroundColor: Colors.green.shade700,
                shape: const CircleBorder(),
              ),
            ),
          ),
        ],
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
            child: TextField(
              controller: _nameController,
              textCapitalization: TextCapitalization.words,
              decoration: InputDecoration(labelText: s.yourName, border: const OutlineInputBorder()),
              onChanged: (_) => setState(() {}),
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Row(
              children: [
                Expanded(
                  child: Text(
                    greekFiltered ? s.pickAStyleGreek : s.pickAStyle,
                    style: const TextStyle(fontWeight: FontWeight.w600),
                  ),
                ),
                TextButton.icon(
                  onPressed: _shuffle,
                  icon: const Icon(Icons.shuffle, size: 18),
                  label: Text(s.shuffle),
                ),
              ],
            ),
          ),
          Expanded(
            // A plain scrollable Column, not ListView.builder — every
            // visible style needs to stay mounted the whole time so
            // `_boundaryKeys[_selectedFamily].currentContext` is always
            // valid when "Use" is pressed. A lazily-built ListView would
            // recycle whichever tile scrolls out of view (e.g. if you pick
            // one style, then scroll down to look at another before
            // hitting Use), leaving the selected tile's RepaintBoundary
            // unmounted.
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(children: [for (final style in visible) _buildStyleTile(style)]),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildStyleTile(_SignatureFontStyle style) {
    final selected = style.fontFamily == _selectedFamily;
    final name = _nameController.text.trim();
    final displayName = name.isEmpty ? AppStrings.of(context).yourNamePlaceholder : name;
    final variant = _variantFor(style.fontFamily);
    return GestureDetector(
      onTap: () => setState(() => _selectedFamily = style.fontFamily),
      child: Container(
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.symmetric(vertical: 18, horizontal: 12),
        decoration: BoxDecoration(
          border: Border.all(
            color: selected ? Colors.deepPurple : Colors.grey.shade300,
            width: selected ? 2 : 1,
          ),
          borderRadius: BorderRadius.circular(12),
          color: selected ? Colors.deepPurple.withValues(alpha: 0.05) : null,
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              style.label,
              style: TextStyle(fontSize: 12, color: Colors.grey.shade600),
            ),
            const SizedBox(height: 4),
            // Only what's inside this RepaintBoundary is ever captured (on
            // "Use") — no border or fill painted in here, so the exported
            // PNG is just the name itself with a real transparent
            // background, exactly like a hand-drawn signature capture.
            // Sized a bit larger than the text itself so the slight
            // shuffle rotation has room without touching the edge.
            RepaintBoundary(
              key: _boundaryKeys[style.fontFamily],
              child: SizedBox(
                width: 300,
                height: 100,
                child: Center(
                  child: Transform.rotate(
                    angle: variant.rotation,
                    child: _buildSignatureText(displayName, style),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  /// Renders [text] in [style]'s font as plain black — the "ink on paper"
  /// look every signature source in this app uses (drawn, typed, or
  /// photographed).
  Widget _buildSignatureText(String text, _SignatureFontStyle style) {
    return Text(
      text,
      style: TextStyle(fontFamily: style.fontFamily, fontSize: style.fontSize, color: Colors.black),
    );
  }
}
